// Auto-generated by: supabase gen types typescript
// Run: supabase gen types typescript --project-id YOUR_PROJECT_ID > packages/supabase/src/database.types.ts

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          role: 'tourist' | 'provider' | 'admin'
          full_name: string | null
          avatar_url: string | null
          phone: string | null
          created_at: string
        }
        Insert: {
          id: string
          role: 'tourist' | 'provider' | 'admin'
          full_name?: string | null
          avatar_url?: string | null
          phone?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          role?: 'tourist' | 'provider' | 'admin'
          full_name?: string | null
          avatar_url?: string | null
          phone?: string | null
          created_at?: string
        }
      }
      providers: {
        Row: {
          id: string
          user_id: string
          business_name: string
          description: string | null
          logo_url: string | null
          location: string | null
          verified: boolean
          rating: number | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          business_name: string
          description?: string | null
          logo_url?: string | null
          location?: string | null
          verified?: boolean
          rating?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          business_name?: string
          description?: string | null
          logo_url?: string | null
          location?: string | null
          verified?: boolean
          rating?: number | null
          created_at?: string
        }
      }
      activities: {
        Row: {
          id: string
          provider_id: string
          title: string
          description: string | null
          category: string
          difficulty: number
          duration_hours: number | null
          price_per_person: number
          max_participants: number
          min_age: number | null
          location: string | null
          latitude: number | null
          longitude: number | null
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          provider_id: string
          title: string
          description?: string | null
          category: string
          difficulty: number
          duration_hours?: number | null
          price_per_person: number
          max_participants: number
          min_age?: number | null
          location?: string | null
          latitude?: number | null
          longitude?: number | null
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          provider_id?: string
          title?: string
          description?: string | null
          category?: string
          difficulty?: number
          duration_hours?: number | null
          price_per_person?: number
          max_participants?: number
          min_age?: number | null
          location?: string | null
          latitude?: number | null
          longitude?: number | null
          is_active?: boolean
          created_at?: string
        }
      }
      activity_images: {
        Row: {
          id: string
          activity_id: string
          url: string
          is_cover: boolean
          order_index: number
        }
        Insert: {
          id?: string
          activity_id: string
          url: string
          is_cover?: boolean
          order_index?: number
        }
        Update: {
          id?: string
          activity_id?: string
          url?: string
          is_cover?: boolean
          order_index?: number
        }
      }
      availability: {
        Row: {
          id: string
          activity_id: string
          date: string
          time: string | null
          total_spots: number
          booked_spots: number
        }
        Insert: {
          id?: string
          activity_id: string
          date: string
          time?: string | null
          total_spots: number
          booked_spots?: number
        }
        Update: {
          id?: string
          activity_id?: string
          date?: string
          time?: string | null
          total_spots?: number
          booked_spots?: number
        }
      }
      bookings: {
        Row: {
          id: string
          tourist_id: string
          activity_id: string
          availability_id: string
          participants: number
          total_price: number
          status: 'pending' | 'confirmed' | 'cancelled' | 'completed'
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          tourist_id: string
          activity_id: string
          availability_id: string
          participants: number
          total_price: number
          status?: 'pending' | 'confirmed' | 'cancelled' | 'completed'
          notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          tourist_id?: string
          activity_id?: string
          availability_id?: string
          participants?: number
          total_price?: number
          status?: 'pending' | 'confirmed' | 'cancelled' | 'completed'
          notes?: string | null
          created_at?: string
        }
      }
      reviews: {
        Row: {
          id: string
          booking_id: string
          tourist_id: string
          activity_id: string
          rating: number
          comment: string | null
          provider_reply: string | null
          created_at: string
        }
        Insert: {
          id?: string
          booking_id: string
          tourist_id: string
          activity_id: string
          rating: number
          comment?: string | null
          provider_reply?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          booking_id?: string
          tourist_id?: string
          activity_id?: string
          rating?: number
          comment?: string | null
          provider_reply?: string | null
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
